baseURL = "https://khubo.github.io"
languageCode = "en-us"
title = "B-Logs"
theme = "yinyang"
DefaultContentLanguage = "en"
publishDir = "docs"

[author]
  name = "B-logs"
  homepage = "https://khubo.github.io/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1 

[params]
mainSections = ["posts"]

[[params.socials]]
name = "github"
link = "https://github.com/khubo"

